//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPrueba.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class registros
    {
        public int IdReg { get; set; }
        public int IdProd { get; set; }
        public int IdCate { get; set; }
        public int IdProv { get; set; }
    
        public virtual categorias categorias { get; set; }
        public virtual productos productos { get; set; }
        public virtual proveedores proveedores { get; set; }
    }
}
